In [76]:
import pandas as pd
import pyodbc

In [77]:
conn = pyodbc.connect('Driver={SQL Server};'
                      'Server=AMIR-PC\SQLEXPRESS;'
                      'Database=training_project;'
                      'Trusted_Connection=yes;')
cursor = conn.cursor()

print('Connected to SQL Server')

Connected to SQL Server

In [78]:
#function for option 1 | add student info

def addStudent():
    id = input("Enter Student ID: ")
    name = input("Enter Student Name: ")
    dob = input("Enter Student DOB: ")
    age = int(input("Enter Student Age: "))
    street = input("Enter Student Street: ")
    state = input("Enter Student State: ")
    country = input("Enter Student Country: ")
    postcode = int(input("Enter Student Postcode: "))
    phone = input("Enter Student Phone: ")
    email = input("Enter Student Email: ")

    cursor.execute("""
        INSERT INTO 
            dbo.Student_Personal 
        VALUES 
            (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    """, (id, name, dob, age, street, state, country, postcode, phone, email))

    conn.commit()
    print('Student information successfully added\n')

In [79]:
#function for option 2 | insert student marks

def addMarks():
    id = input("Enter Student ID: ")
    malay = int(input("Enter marks for Malay:"))
    english = int(input("Enter marks for English:"))
    science = int(input("Enter marks for Science:"))
    maths = int(input("Enter marks for Maths:"))
    arts = int(input("Enter marks for Arts:"))
    history = int(input("Enter marks for History:"))
    geography = int(input("Enter marks for Geography:"))

    total = malay + english + science + maths + arts + history + geography
    average = total / 7

    if average >= 80:
        result = 'PASS'
        grade = 'A'
    elif average >= 70:
        result = 'PASS'
        grade = 'B'  
    elif average >= 60:
        result = 'PASS'
        grade = 'C'
    elif average >= 50:
        result = 'PASS'
        grade = 'D'
    else:
        result = 'FAIL'
        grade = 'F'

    cursor.execute("""
        INSERT INTO 
            dbo.Student_Marks 
        VALUES 
            (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    """, (id, malay, english, science, maths, arts, history, geography, total, average, result, grade))

    conn.commit()
    print('Student marks successfully added\n')

In [80]:
#function for option 3 | update student info

def updateStudent():
    id = int(input("Enter Student ID to update: "))

    print('What to update?')
    print('1. Student Name')
    print('2. Student DOB')
    print('3. Student Age')
    print('4. Student Street')
    print('5. Student State')
    print('6. Student Country')
    print('7. Student Postcode')
    print('8. Student Phone')
    print('9. Student Email\n')

    menu = int(input('Enter your choice: '))

    if menu == 1:
        update = input("Enter Student Name: ")
        cursor.execute("UPDATE dbo.Student_Personal SET Std_Name = '%s' WHERE Std_ID = %d " %(update, id))
    elif menu == 2:
        update = input("Enter Student DOB: ")
        cursor.execute("UPDATE dbo.Student_Personal SET Std_DOB = '%s' WHERE Std_ID = %d " %(update, id))
    elif menu == 3:
        update = int(input("Enter Student Age: "))
        cursor.execute("UPDATE dbo.Student_Personal SET Std_Age = %d WHERE Std_ID = %d " %(update, id))
    elif menu == 4:
        update = input("Enter Student Street: ")
        cursor.execute("UPDATE dbo.Student_Personal SET Std_Street = '%s' WHERE Std_ID = %d " %(update, id))
    elif menu == 5:
        update = input("Enter Student State: ")
        cursor.execute("UPDATE dbo.Student_Personal SET Std_State = '%s' WHERE Std_ID = %d " %(update, id))
    elif menu == 6:
        update = input("Enter Student Country: ")
        cursor.execute("UPDATE dbo.Student_Personal SET Std_Country = '%s' WHERE Std_ID = %d " %(update, id))
    elif menu == 7:
        update = int(input("Enter Student Postcode: "))
        cursor.execute("UPDATE dbo.Student_Personal SET Std_Postcode = %d WHERE Std_ID = %d " %(update, id))
    elif menu == 8:
        update = input("Enter Student Phone: ")
        cursor.execute("UPDATE dbo.Student_Personal SET Std_Phone = '%s' WHERE Std_ID = %d " %(update, id))
    elif menu == 9:
        update = input("Enter Student Email: ")
        cursor.execute("UPDATE dbo.Student_Personal SET Std_Email = '%s' WHERE Std_ID = %d " %(update, id))
    else:
        print('Invalid input')
    
    conn.commit()
    print('Student information successfully updated\n')

In [81]:
#function for option 4 | delete student info

def deleteStudent():
    id = int(input("Enter Student ID to delete: "))
    cursor.execute("DELETE FROM dbo.Student_Personal WHERE Std_ID = %d " %(id))
    conn.commit()
    
    print('Student information successfully deleted\n')

In [82]:
#function for option 5 | search student info

def searchStudent():
    id = int(input("Enter Student ID to search: "))

    cursor.execute('''
                SELECT * 
                FROM Student_Personal
                LEFT JOIN Student_Marks ON Student_Personal.Std_ID = Student_Marks.Std_ID
                WHERE Student_Personal.Std_ID = ?
                '''
                , id)
    row = cursor.fetchone()

    if row == None:
        print('Student not found')
    else:
        print('Student found')
        print('------------DETAILS--------------')
        print('Student ID: ', row[0])
        print('Student Name: ', row[1])
        print('Student DOB: ', row[2])
        print('Student Age: ', row[3])
        print('Student Street: ', row[4])
        print('Student State: ', row[5])
        print('Student Country: ', row[6])
        print('Student Postcode: ', row[7])
        print('Student Phone: ', row[8])
        print('Student Email: ', row[9])
        print('\n-------------MARKS---------------')
        print('Student Malay Marks: ', row[11])
        print('Student English Marks: ', row[12])
        print('Student Science Marks: ', row[13])
        print('Student Maths Marks: ', row[14])
        print('Student Arts Marks: ', row[15])
        print('Student History Marks: ', row[16])
        print('Student Geography Marks: ', row[17])
        print('\nGrade: ', row[21])
        print('Result: ', row[20])
        print('\n')

    conn.commit()

    print('Student info displayed\n')

In [83]:
#function for option 6 | display all student report

def displayReport():
    cursor.execute('''
                SELECT * 
                FROM Student_Personal
                LEFT JOIN Student_Marks ON Student_Personal.Std_ID = Student_Marks.Std_ID
                ''')
    rows = cursor.fetchall()

    for row in rows:
        print('------------DETAILS--------------')
        print('Student ID: ', row[0])
        print('Student Name: ', row[1])
        print('Student DOB: ', row[2])
        print('Student Age: ', row[3])
        print('Student Street: ', row[4])
        print('Student State: ', row[5])
        print('Student Country: ', row[6])
        print('Student Postcode: ', row[7])
        print('Student Phone: ', row[8])
        print('Student Email: ', row[9])
        print('\n-------------MARKS---------------')
        print('Student Malay Marks: ', row[11])
        print('Student English Marks: ', row[12])
        print('Student Science Marks: ', row[13])
        print('Student Maths Marks: ', row[14])
        print('Student Arts Marks: ', row[15])
        print('Student History Marks: ', row[16])
        print('Student Geography Marks: ', row[17])
        print('\nGrade: ', row[21])
        print('Result: ', row[20])
        print('\n')

    conn.commit()

    print('All student info displayed\n')

In [84]:
def print_menu():       ## Your menu design here
    print('STUDENT MANAGEMENT SYSTEM\n')

    print('1. Add a new student information')
    print('2. Insert student marks')
    print('3. Update student information')
    print('4. Delete student information')
    print('5. Search student information')
    print('6. Display all student report')
    print('0. Exit')
    print()

In [85]:
while(True):
    print_menu()
    option = ''
    try:
        option = int(input('Enter your choice: '))
    except:
        print('Wrong input. Please enter a number ...')

    if option == 1:
        addStudent()
    elif option == 2:
        addMarks()
    elif option == 3:
        updateStudent()
    elif option == 4:
        deleteStudent()
    elif option == 5:
        searchStudent()
    elif option == 6:
        displayReport()
    elif option == 0:
        print('Exiting...')
        break
    else:
        print('Invalid option. Please enter a number between 1 and 6.\n')

STUDENT MANAGEMENT SYSTEM

1. Add a new student information
2. Insert student marks
3. Update student information
4. Delete student information
5. Search student information
6. Display all student report
0. Exit

------------DETAILS--------------
Student ID:  101
Student Name:  Preeta a/l Merican
Student DOB:  1979-03-31
Student Age:  43
Student Street:  No. 36 Jln Yong Shook Lin Seksyen 52
Student State:  Selangor
Student Country:  Malaysia
Student Postcode:  46200
Student Phone:  0125551111
Student Email:  preeta@gmail.com

-------------MARKS---------------
Student Malay Marks:  85
Student English Marks:  60
Student Science Marks:  52
Student Maths Marks:  62
Student Arts Marks:  99
Student History Marks:  33
Student Geography Marks:  57

Grade:  C
Result:  PASS


------------DETAILS--------------
Student ID:  102
Student Name:  Siauw Koong Cheng
Student DOB:  1980-06-01
Student Age:  42
Student Street:  13A Jln Pudu Ulu
Student State:  Kuala Lumpur
Student Country:  Malaysia
Student Postcode:  56100
Student Phone:  0125551112
Student Email:  siauw@gmail.com

-------------MARKS---------------
Student Malay Marks:  55
Student English Marks:  65
Student Science Marks:  75
Student Maths Marks:  35
Student Arts Marks:  78
Student History Marks:  31
Student Geography Marks:  43

Grade:  D
Result:  PASS


------------DETAILS--------------
Student ID:  103
Student Name:  Muhammad Haji Syed Aidi
Student DOB:  1980-10-19
Student Age:  41
Student Street:  1 6 Jln Pjs 11/8 Taman Bandar Sunway
Student State:  Selangor
Student Country:  Malaysia
Student Postcode:  46150
Student Phone:  0125551113
Student Email:  muhammad@gmail.com

-------------MARKS---------------
Student Malay Marks:  88
Student English Marks:  81
Student Science Marks:  56
Student Maths Marks:  77
Student Arts Marks:  65
Student History Marks:  29
Student Geography Marks:  73

Grade:  C
Result:  PASS


------------DETAILS--------------
Student ID:  104
Student Name:  Veloo Munusamy
Student DOB:  1980-11-23
Student Age:  41
Student Street:  32B Jalan Pekaka 8/3 Kota Damansara
Student State:  Selangor
Student Country:  Malaysia
Student Postcode:  47810
Student Phone:  0125551114
Student Email:  veloo@gmail.com

-------------MARKS---------------
Student Malay Marks:  22
Student English Marks:  95
Student Science Marks:  64
Student Maths Marks:  92
Student Arts Marks:  60
Student History Marks:  47
Student Geography Marks:  22

Grade:  D
Result:  PASS


------------DETAILS--------------
Student ID:  105
Student Name:  Philip Nguei Ong Khoi
Student DOB:  1981-06-10
Student Age:  41
Student Street:  No. 8 Jalan 4/91A Taman Shamelin Perkasa Batu
Student State:  Kuala Lumpur
Student Country:  Malaysia
Student Postcode:  56100
Student Phone:  0125551115
Student Email:  philip@gmail.com

-------------MARKS---------------
Student Malay Marks:  28
Student English Marks:  74
Student Science Marks:  25
Student Maths Marks:  75
Student Arts Marks:  43
Student History Marks:  39
Student Geography Marks:  90

Grade:  D
Result:  PASS


------------DETAILS--------------
Student ID:  106
Student Name:  Noor Zulaikha Rosnan binti Syawal
Student DOB:  1981-07-06
Student Age:  41
Student Street:  9-1 Jalan 13/142 Taman Orkid Desa
Student State:  Kuala Lumpur
Student Country:  Malaysia
Student Postcode:  56000
Student Phone:  0125551116
Student Email:  noor@gmail.com

-------------MARKS---------------
Student Malay Marks:  82
Student English Marks:  76
Student Science Marks:  89
Student Maths Marks:  37
Student Arts Marks:  66
Student History Marks:  28
Student Geography Marks:  61

Grade:  C
Result:  PASS


------------DETAILS--------------
Student ID:  107
Student Name:  Muhammed Wan Muazzam Zulkernain
Student DOB:  1982-06-01
Student Age:  40
Student Street:  18 Jln Lapangan Terbang Lama
Student State:  Kuala Lumpur
Student Country:  Malaysia
Student Postcode:  50460
Student Phone:  0125551117
Student Email:  muhammed@gmail.com

-------------MARKS---------------
Student Malay Marks:  40
Student English Marks:  65
Student Science Marks:  24
Student Maths Marks:  65
Student Arts Marks:  47
Student History Marks:  38
Student Geography Marks:  24

Grade:  F
Result:  FAIL


------------DETAILS--------------
Student ID:  108
Student Name:  Selva Muniandy
Student DOB:  1984-08-14
Student Age:  38
Student Street:  Jalan 20/7, Paramount Garden
Student State:  Selangor
Student Country:  Malaysia
Student Postcode:  46300
Student Phone:  0125551118
Student Email:  selva@gmail.com

-------------MARKS---------------
Student Malay Marks:  90
Student English Marks:  20
Student Science Marks:  21
Student Maths Marks:  48
Student Arts Marks:  57
Student History Marks:  58
Student Geography Marks:  95

Grade:  D
Result:  PASS


------------DETAILS--------------
Student ID:  109
Student Name:  Daniel Seah Zeng Shing
Student DOB:  1985-03-06
Student Age:  37
Student Street:  Perdana Business Centre, Bandar Damansara Perdana
Student State:  Selangor
Student Country:  Malaysia
Student Postcode:  47820
Student Phone:  0125551119
Student Email:  daniel@gmail.com

-------------MARKS---------------
Student Malay Marks:  71
Student English Marks:  91
Student Science Marks:  37
Student Maths Marks:  67
Student Arts Marks:  38
Student History Marks:  23
Student Geography Marks:  30

Grade:  D
Result:  PASS


------------DETAILS--------------
Student ID:  110
Student Name:  Viatilingam Vadiveloo
Student DOB:  1986-12-02
Student Age:  35
Student Street:  No 142-146, Jalan Tuanku Abdul Rahman
Student State:  Kuala Lumpur
Student Country:  Malaysia
Student Postcode:  50100
Student Phone:  0125551120
Student Email:  viatilingam@gmail.com

-------------MARKS---------------
Student Malay Marks:  43
Student English Marks:  64
Student Science Marks:  25
Student Maths Marks:  37
Student Arts Marks:  54
Student History Marks:  31
Student Geography Marks:  59

Grade:  F
Result:  FAIL


------------DETAILS--------------
Student ID:  111
Student Name:  Rafidah Yacob binti Nik Tayib
Student DOB:  1987-07-30
Student Age:  35
Student Street:  57, JALAN WANGSA JAYA TAMAN WANGSA JAYA
Student State:  Kuala Lumpur
Student Country:  Malaysia
Student Postcode:  53300
Student Phone:  0125551121
Student Email:  rafidah@gmail.com

-------------MARKS---------------
Student Malay Marks:  97
Student English Marks:  26
Student Science Marks:  40
Student Maths Marks:  27
Student Arts Marks:  40
Student History Marks:  57
Student Geography Marks:  76

Grade:  D
Result:  PASS


------------DETAILS--------------
Student ID:  112
Student Name:  Preeta a/l Kasinather
Student DOB:  1989-02-20
Student Age:  33
Student Street:  Lot 117 New Commercial Centre Batu Niah
Student State:  Sarawak
Student Country:  Malaysia
Student Postcode:  98200
Student Phone:  0125551122
Student Email:  preeta2@gmail.com

-------------MARKS---------------
Student Malay Marks:  27
Student English Marks:  39
Student Science Marks:  21
Student Maths Marks:  65
Student Arts Marks:  69
Student History Marks:  37
Student Geography Marks:  22

Grade:  F
Result:  FAIL


------------DETAILS--------------
Student ID:  113
Student Name:  Leow Say Shee
Student DOB:  1989-07-11
Student Age:  33
Student Street:  10-2 Jln Perubatan 3 Taman Pandan Indah
Student State:  Kuala Lumpur
Student Country:  Malaysia
Student Postcode:  55100
Student Phone:  0125551123
Student Email:  leow@gmail.com

-------------MARKS---------------
Student Malay Marks:  71
Student English Marks:  48
Student Science Marks:  56
Student Maths Marks:  29
Student Arts Marks:  34
Student History Marks:  98
Student Geography Marks:  44

Grade:  D
Result:  PASS


------------DETAILS--------------
Student ID:  114
Student Name:  Lim Ceh Khoo
Student DOB:  1991-05-01
Student Age:  31
Student Street:  2 9B Jln Sarikei
Student State:  Kuala Lumpur
Student Country:  Malaysia
Student Postcode:  53000
Student Phone:  0125551124
Student Email:  lim@gmail.com

-------------MARKS---------------
Student Malay Marks:  75
Student English Marks:  45
Student Science Marks:  95
Student Maths Marks:  75
Student Arts Marks:  74
Student History Marks:  95
Student Geography Marks:  66

Grade:  B
Result:  PASS


------------DETAILS--------------
Student ID:  115
Student Name:  Siow Feng Shei
Student DOB:  1995-02-17
Student Age:  27
Student Street:  25B Jln Pjs 10/32 Taman Sri Subang
Student State:  Selangor
Student Country:  Malaysia
Student Postcode:  46000
Student Phone:  0125551125
Student Email:  siow@gmail.com

-------------MARKS---------------
Student Malay Marks:  35
Student English Marks:  57
Student Science Marks:  39
Student Maths Marks:  70
Student Arts Marks:  83
Student History Marks:  89
Student Geography Marks:  96

Grade:  C
Result:  PASS


------------DETAILS--------------
Student ID:  116
Student Name:  Er Sham Lau
Student DOB:  1995-04-02
Student Age:  27
Student Street:  No 89 Jalan Belibis 5 Taman Perling
Student State:  Johor
Student Country:  Malaysia
Student Postcode:  81200
Student Phone:  0125551126
Student Email:  er@gmail.com

-------------MARKS---------------
Student Malay Marks:  82
Student English Marks:  50
Student Science Marks:  92
Student Maths Marks:  60
Student Arts Marks:  62
Student History Marks:  59
Student Geography Marks:  64

Grade:  C
Result:  PASS


------------DETAILS--------------
Student ID:  117
Student Name:  Hjh Azua binti Norazmi
Student DOB:  1996-05-17
Student Age:  26
Student Street:  Jalan SS23/11, Taman Sea,
Student State:  Selangor
Student Country:  Malaysia
Student Postcode:  47400
Student Phone:  0125551127
Student Email:  hjh1@gmail.com

-------------MARKS---------------
Student Malay Marks:  92
Student English Marks:  44
Student Science Marks:  36
Student Maths Marks:  96
Student Arts Marks:  75
Student History Marks:  98
Student Geography Marks:  34

Grade:  C
Result:  PASS


------------DETAILS--------------
Student ID:  118
Student Name:  Hjh Nurfaizah Nazry
Student DOB:  1996-05-23
Student Age:  26
Student Street:  Gpo Box 50736
Student State:  Kuala Lumpur
Student Country:  Malaysia
Student Postcode:  11140
Student Phone:  0125551128
Student Email:  hjh2@gmail.com

-------------MARKS---------------
Student Malay Marks:  63
Student English Marks:  71
Student Science Marks:  39
Student Maths Marks:  64
Student Arts Marks:  89
Student History Marks:  51
Student Geography Marks:  51

Grade:  C
Result:  PASS


------------DETAILS--------------
Student ID:  119
Student Name:  Sanjay a/l Rajeswary
Student DOB:  1996-12-10
Student Age:  25
Student Street:  Level 9 Menara Chan 138 Jalan Ampang
Student State:  Kuala Lumpur
Student Country:  Malaysia
Student Postcode:  50450
Student Phone:  0125551129
Student Email:  sanjay@gmail.com

-------------MARKS---------------
Student Malay Marks:  77
Student English Marks:  95
Student Science Marks:  84
Student Maths Marks:  36
Student Arts Marks:  48
Student History Marks:  59
Student Geography Marks:  48

Grade:  C
Result:  PASS


------------DETAILS--------------
Student ID:  120
Student Name:  Thong Khaw Lui
Student DOB:  1996-12-11
Student Age:  25
Student Street:  1 Jln Temenggong Kangkar Tebrau
Student State:  Johor
Student Country:  Malaysia
Student Postcode:  81100
Student Phone:  0125551130
Student Email:  thong@gmail.com

-------------MARKS---------------
Student Malay Marks:  99
Student English Marks:  91
Student Science Marks:  91
Student Maths Marks:  98
Student Arts Marks:  99
Student History Marks:  85
Student Geography Marks:  55

Grade:  A
Result:  PASS


------------DETAILS--------------
Student ID:  121
Student Name:  Nurul Emylia Lukman binti Firdaus
Student DOB:  1997-02-04
Student Age:  25
Student Street:  7 Wisma Central Jln Ampang
Student State:  Kuala Lumpur
Student Country:  Malaysia
Student Postcode:  50450
Student Phone:  0125551131
Student Email:  nurul@gmail.com

-------------MARKS---------------
Student Malay Marks:  64
Student English Marks:  49
Student Science Marks:  38
Student Maths Marks:  96
Student Arts Marks:  87
Student History Marks:  52
Student Geography Marks:  61

Grade:  C
Result:  PASS


------------DETAILS--------------
Student ID:  122
Student Name:  Samad Lourdenadin
Student DOB:  1998-03-21
Student Age:  24
Student Street:  gleneagles intan medical centre 282, jalan ampang,
Student State:  Kuala Lumpur
Student Country:  Malaysia
Student Postcode:  50450
Student Phone:  0125551132
Student Email:  samad@gmail.com

-------------MARKS---------------
Student Malay Marks:  41
Student English Marks:  62
Student Science Marks:  46
Student Maths Marks:  55
Student Arts Marks:  40
Student History Marks:  54
Student Geography Marks:  24

Grade:  F
Result:  FAIL


------------DETAILS--------------
Student ID:  123
Student Name:  Teng Chai Pooi
Student DOB:  1998-07-12
Student Age:  24
Student Street:  29 Jln 10/32 Taman Jinjang Baru
Student State:  Kuala Lumpur
Student Country:  Malaysia
Student Postcode:  52000
Student Phone:  0125551133
Student Email:  teng@gmail.com

-------------MARKS---------------
Student Malay Marks:  41
Student English Marks:  27
Student Science Marks:  61
Student Maths Marks:  63
Student Arts Marks:  30
Student History Marks:  34
Student Geography Marks:  22

Grade:  F
Result:  FAIL


------------DETAILS--------------
Student ID:  124
Student Name:  Syahidatul Rohman binti Suhiman
Student DOB:  1998-11-12
Student Age:  23
Student Street:  No. 1, Huo Ping Road
Student State:  Kuala Lumpur
Student Country:  Malaysia
Student Postcode:  96008
Student Phone:  0125551134
Student Email:  syahidatul@gmail.com

-------------MARKS---------------
Student Malay Marks:  94
Student English Marks:  85
Student Science Marks:  46
Student Maths Marks:  70
Student Arts Marks:  99
Student History Marks:  67
Student Geography Marks:  71

Grade:  B
Result:  PASS


------------DETAILS--------------
Student ID:  125
Student Name:  Chan Ong Tew
Student DOB:  1999-06-14
Student Age:  23
Student Street:  1 36E Jln Petani Kuala
Student State:  Terengganu
Student Country:  Malaysia
Student Postcode:  20000
Student Phone:  0125551135
Student Email:  chan@gmail.com

-------------MARKS---------------
Student Malay Marks:  26
Student English Marks:  100
Student Science Marks:  22
Student Maths Marks:  31
Student Arts Marks:  75
Student History Marks:  60
Student Geography Marks:  90

Grade:  D
Result:  PASS


------------DETAILS--------------
Student ID:  126
Student Name:  Renuga a/l Govindasamy
Student DOB:  1996-11-02
Student Age:  25
Student Street:  31-2 Jalan 45A/26 Taman Rampai Setapak
Student State:  Kuala Lumpur
Student Country:  Malaysia
Student Postcode:  53300
Student Phone:  0125551136
Student Email:  renuga@gmail.com

-------------MARKS---------------
Student Malay Marks:  52
Student English Marks:  23
Student Science Marks:  88
Student Maths Marks:  26
Student Arts Marks:  70
Student History Marks:  37
Student Geography Marks:  40

Grade:  F
Result:  FAIL


------------DETAILS--------------
Student ID:  127
Student Name:  Lai Tung Shou
Student DOB:  1996-12-16
Student Age:  25
Student Street:  1 Blok F Diamond Square Jln 4/50
Student State:  Kuala Lumpur
Student Country:  Malaysia
Student Postcode:  53000
Student Phone:  0125551137
Student Email:  lai@gmail.com

-------------MARKS---------------
Student Malay Marks:  88
Student English Marks:  73
Student Science Marks:  64
Student Maths Marks:  95
Student Arts Marks:  91
Student History Marks:  91
Student Geography Marks:  23

Grade:  B
Result:  PASS


------------DETAILS--------------
Student ID:  128
Student Name:  Yeong Chia Shi
Student DOB:  1997-03-04
Student Age:  25
Student Street:  No. 2742 Jln Changkat Permata Taman Permata Hulu
Student State:  Selangor
Student Country:  Malaysia
Student Postcode:  53300
Student Phone:  0125551138
Student Email:  yeong@gmail.com

-------------MARKS---------------
Student Malay Marks:  24
Student English Marks:  42
Student Science Marks:  42
Student Maths Marks:  87
Student Arts Marks:  21
Student History Marks:  68
Student Geography Marks:  54

Grade:  F
Result:  FAIL


------------DETAILS--------------
Student ID:  129
Student Name:  Kula L. Ramesh
Student DOB:  1997-04-03
Student Age:  25
Student Street:  13 Jln Dato Sheikh Ahmad
Student State:  Negeri Sembilan
Student Country:  Malaysia
Student Postcode:  70000
Student Phone:  0125551139
Student Email:  kula@gmail.com

-------------MARKS---------------
Student Malay Marks:  24
Student English Marks:  82
Student Science Marks:  72
Student Maths Marks:  29
Student Arts Marks:  24
Student History Marks:  89
Student Geography Marks:  84

Grade:  D
Result:  PASS


------------DETAILS--------------
Student ID:  130
Student Name:  Shum Ngah Yup
Student DOB:  1998-10-02
Student Age:  23
Student Street:  alan Permas 10, Bandar Baru Permas Jaya
Student State:  Johor
Student Country:  Malaysia
Student Postcode:  81750
Student Phone:  0125551140
Student Email:  shum@gmail.com

-------------MARKS---------------
Student Malay Marks:  24
Student English Marks:  69
Student Science Marks:  64
Student Maths Marks:  62
Student Arts Marks:  58
Student History Marks:  82
Student Geography Marks:  61

Grade:  C
Result:  PASS


All student info displayed

STUDENT MANAGEMENT SYSTEM

1. Add a new student information
2. Insert student marks
3. Update student information
4. Delete student information
5. Search student information
6. Display all student report
0. Exit

Exiting...